### ISSUE TITLE
404 error with loading anatomicals

### ISSUE THREAD

**Issue by iancballard** [mwaskom/ziegler#13]
I get the following error when attempting to view the outputs of anatomy_snapshots.py. I have verified that the files exist in this location and am starting ziegler from within LYMAN_DIR (and static is located in LYMAN_DIR/static)

![screen shot 2015-04-29 at 12 11 40 pm](https://cloud.githubusercontent.com/assets/5826949/7399244/4c5a50de-ee69-11e4-9e50-6b22781a7c1c.png)

**Comment by mwaskom** [comment]
You should start ziegler from the directly where ziegler.py lives.

**Comment by iancballard** [comment]
thanks that did the trick
