### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by iancballard** [mwaskom/ziegler#14]
Not an issue, but if you ever decide to expand ziegler, it would be nice to be able to use it to look at snapshots of raw functional data. This would be nice for checking mux reconstructions or field map correction results, for example.

**Comment by mwaskom** [comment]
The motion correction target plot is more or less as raw as it gets, unless you mean something different.

**Comment by iancballard** [comment]
Ah, I had not done full preprocessing yet, as I'm still doing some initial preprocessing (topup) and QA and I typically examine my data at this step. Seems easy enough to hold off until after running full preprocessing. Thanks.

**Comment by mwaskom** [comment]
It can still be good to look at the full timeseries but the motion correction target should alert you to really large problems in the raw data (you'll see it in the mean functional too).
